name: dsp
channels:
  - conda-forge            # Note: the order listed in yaml is not enforced by conda
  - nodefaults               # For predictable behavior, set your conda config
  - cadwr-dms
dependencies:
  - python=3.8
  - schimpy
  - dms-datastore
  - pyhecdss
  - pip
  - matplotlib
  - pandas
  - dask
  - xarray
  - scipy
  - holoviews
  - hvplot
  - panel
#  - ipykernel  
  - pillow == 9.0.1 
  
# Install the following with command line
#  pip install -e git+https://github.com/CADWRDeltaModeling/pydelmod#egg=pydelmod
#  pip install -e git+https://github.com/CADWRDeltaModeling/pydsm#egg=pydsm

# pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org tensorflow
# pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org keras-tuner
# pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org openpyxl==3.0.7

# - scikit-learn