## This script is to check the Net Delta Outflow of a simulation that has 
## already run using the boundaries generated by the previous scripts


# Libraries commonly used -------------------------------------------------

library(lubridate)
library(reshape2)
library(ggplot2)
library(plotly)
library(zoo)
library(hash)
# library(readxl)
library(htmlwidgets)
library(stringr)
library(scales)
library(yaml)
library(RColorBrewer)

# Set wd to current file --------------------------------------------------

rm(list=ls(all=TRUE)) #start with empty workspace
setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) # Setworking directory to this file's directory
source("./functions/load_delta_vars.R")

# Define variables ---------------------------------------------------------

experiment <- 'latinhypercube_v2'

dsm2.dir <- '../../model/dsm2/DSP_DSM2_202307/'

cases <- seq(1,7)

sheetlist <- c("northern_flow","sjr_flow","exports","dxc_gate_fraction",
               "suisun_gate_fraction","net_delta_cu","mtz_tidal_nrg",
               "base_ec_output")
sheetnames <- c('Northern Flow', 'SJR Flow','Exports','DCC Gate',
                'Suisun Gate','Consump Use','Tidal Nrg')

in_yml <- '../ann_training/input/lathypcub_v2_ann_config.yaml' 

plt.vars <- append('hist', cases)
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

var.cols <- append('black',sample(col_vector, length(cases)))
pie(rep(1,length(var.cols)), col=var.cols)

# Load data ---------------------------------------------------------------


# ``` load yaml defs of case periods --------------------------------------

lhc_setup <- suppressWarnings(yaml.load_file(in_yml))

case.dts <- data.frame(matrix(NA,
                              nrow <- length(cases),
                              ncol <- 3))
names(case.dts) <- c('case','dt.min','dt.max')
# case.dts$case <- cases
train_setup <- lhc_setup$train_config

for (trs in train_setup) {
  c <- trs[['num']]
  if (c==0) {
    NULL
  } else {
    case.dts[c,'case'] <- c
    case.dts[c,'dt.min'] <- trs[['start']]
    case.dts[c,'dt.max'] <- trs[['end']]
  }
}


# ``` load historical data ----------------------------------------------------

dsm2_filename <- paste0(dsm2.dir,'historical/anninputs/dsm2_ann_inputs_historical.xlsx')

for (sheet in sheetlist){
  assign(sheet,load_delta_vars(dsm2_filename, sheet))
}

# Combine all but base_ec_output
for (var in sheetlist[-length(sheetlist)]) {
  vardf <- get(var)
  if (var==sheetlist[1]){
    delta_state <- vardf
  } else {
    delta_state <- merge(delta_state, vardf, by='Time')
  } # end if var==sheetlist[1]
} # end for var in sheetlist
names(delta_state) <- append(c('Time'), sheetnames)
names(base_ec_output) <- append(c('Time'),names(base_ec_output)[2:ncol(base_ec_output)])
delta_state$`Net Delta Outflow` <- delta_state$`Northern Flow` + delta_state$`SJR Flow` - delta_state$Exports - 
  delta_state$`Consump Use`

ds.df <- melt(delta_state, id.vars='Time')
ds.df$case <- 'hist'
ec.df <- melt(base_ec_output, id.vars='Time')
ec.df$case <- 'hist'
  


# ``` load experimental data --------------------------------------------------

for (c in cases) {
  print(c)
  # load delta state vars
  dsm2_filename <- paste0(dsm2.dir,experiment,'/anninputs/dsm2_ann_inputs_lhc_',c,'.xlsx')
  
  for (sheet in sheetlist){
    assign(sheet,load_delta_vars(dsm2_filename, sheet))
  }
  
  # Combine all but base_ec_output
  for (var in sheetlist[-length(sheetlist)]) {
    vardf <- get(var)
    if (var==sheetlist[1]){
      delta_state <- vardf
    } else {
      delta_state <- merge(delta_state, vardf, by='Time')
    } # end if var==sheetlist[1]
  } # end for var in sheetlist
  names(delta_state) <- append(c('Time'), sheetnames)
  names(base_ec_output) <- append(c('Time'),names(base_ec_output)[2:ncol(base_ec_output)])
  
  # trim to case
  delta_state <- delta_state[delta_state$Time>=case.dts$dt.min[c] & delta_state$Time<=case.dts$dt.max[c],]
  
  delta_state$`Net Delta Outflow` <- delta_state$`Northern Flow` + delta_state$`SJR Flow` - delta_state$Exports - 
    delta_state$`Consump Use`
  
  dsdum <- melt(delta_state, id.vars='Time')
  dsdum$case <- c
  ecdum <- melt(base_ec_output, id.vars='Time')
  ecdum$case <- c
  
  ds.df <- rbind(ds.df, dsdum)
  ec.df <- rbind(ec.df, ecdum)
  
  rm(list=(append(sheetlist, c('dsdum','ecdum'))))
  # rm(list=setdiff(ls(),c("ds.df","ec.df","experiment","dsm2.dir","cases","c","sheetlist","sheetnames","load_delta_vars","case.dts")))
}

ds.df$Time <- lubridate::ymd(ds.df$Time)
ec.df$Time <- lubridate::ymd(ec.df$Time)

ds.df$case <- factor(ds.df$case,
                     levels=plt.vars)

# Plot inputs -------------------------------------------------------------


date.lims <- c(min(ec.df$Time[ec.df$case %in% cases]),
               max(ec.df$Time[ec.df$case %in% cases]))
# unique(ds.df$variable)

plt <- ggplot(data=ds.df) + 
  geom_line(aes(x=Time, y=value, color=case, linewidth=case)) +
  facet_wrap(~variable, ncol=1, scales='free_y') +
  scale_x_date(limits=date.lims) + 
  ggh4x::scale_y_facet(
    variable == "Northern Flow",
    trans  = "log10",
    breaks = breaks_log(),
    labels = label_log()
  ) +
  ggh4x::scale_y_facet(
    variable == "SJR Flow",
    trans  = "log10",
    breaks = breaks_log(),
    labels = label_log()
  ) +
  ggh4x::scale_y_facet(
    variable == "Net Delta Outflow",
    trans  = "log10",
    breaks = breaks_log(),
    labels = label_log()
  ) +
  scale_color_manual(values=var.cols, breaks=plt.vars) +
  scale_linewidth_manual(values=append(1.5,rep(1,length(cases))), breaks=plt.vars)

plt

pltl <- ggplotly(plt, dynamicTicks=TRUE)
pltl




