## This script is to check the Net Delta Outflow of a simulation that has 
## already run using the boundaries generated by the previous scripts


# Libraries commonly used -------------------------------------------------

library(lubridate)
library(reshape2)
library(ggplot2)
library(plotly)
library(zoo)
library(hash)
library(dplyr)
# library(readxl)
library(htmlwidgets)
library(stringr)
library(scales)
library(yaml)
library(RColorBrewer)

# Set wd to current file --------------------------------------------------

rm(list=ls(all=TRUE)) #start with empty workspace
setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) # Setworking directory to this file's directory
source("./functions/load_delta_vars.R")

# Define variables ---------------------------------------------------------

exp.num <- 3
experiment <- paste0('latinhypercube_v', exp.num)

dsm2.dir <- '../../model/dsm2/DSP_DSM2_202307/'

cases <- seq(1,7)

sheetlist <- c("northern_flow","sjr_flow","exports","dxc_gate_fraction",
               "suisun_gate_fraction","net_delta_cu","mtz_tidal_nrg",
               "base_ec_output")
sheetnames <- c('Northern Flow', 'SJR Flow','Exports','DCC Gate',
                'Suisun Gate','Consump Use','Tidal Nrg')

lhc_yml <-paste0('./input/lathypcub_v',exp.num,'_setup.yaml')
ann_yml <- paste0('../ann_training/input/lathypcub_v',exp.num,'_ann_config.yaml') 

plt.vars <- append('hist', cases)
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))

# var.cols <- append('black',sample(col_vector, length(cases)))
var.cols <- c("black","#BC80BD","#E6AB02","#A6D854","#80B1D3","#984EA3","#E7298A","#4DAF4A")
# pie(rep(1,length(var.cols)), col=var.cols)

set.ec.order <- c("SLMZU011-MONTEZUMA SL AT BELDONS LANDING", #-121.97080
                  "RSAC075-MALLARDISLAND", # -121.92009
                  "RSAC081-COLLINSVILLE", # -121.85012
                  "RSAC092-EMMATON", # 	-121.73892
                  "RSAN018-JERSEYPOINT", # -121.68897
                  "RSAN032-SACRAMENTO R AT SAN ANDREAS LANDING", #	-121.59131
                  "CHSWP003-CCFB_INTAKE", # -121.55740,
                  "ROLD024-OLD RIVER AT BACON ISLAND", # -121.57222
                  "CHDMC006-CVP INTAKE", # -121.54214
                  "CHVCT000-VICTORIA INTAKE" #	-121.52830
) # longitudes
# Load data ---------------------------------------------------------------


# ``` load yaml defs of case periods --------------------------------------

lhc_setup <- suppressWarnings(yaml.load_file(lhc_yml))
ann_setup <- suppressWarnings(yaml.load_file(ann_yml))
train_setup <- ann_setup$train_config

lhc.dts <- data.frame(matrix(NA,
                             nrow <- length(cases),
                             ncol <- 3))
names(lhc.dts) <- c('case','dt.min','dt.max')
ann.dts <- lhc.dts


print("LHC Date Setup------")
for (trs in lhc_setup$cases) {
  name <- trs[['name']]
  if ('0' %in% name) {
    print(paste0("Empty Case: ",name))
    NULL
  } else {
    c <- as.numeric(gsub(".*?([0-9]+).*", "\\1", name))   
    print(paste0("case: ",c," Start: ",trs[['case_start']]," End: ",trs[['case_end']]))
    lhc.dts[c,'case'] <- c
    lhc.dts[c,'dt.min'] <- trs[['case_start']]
    lhc.dts[c,'dt.max'] <- trs[['case_end']]
  }
}

print("ANN Date Setup------")
for (trs in train_setup) {
  c <- trs[['num']]
  if (c==0) {
    print(paste0("Empty Case: ",c," Year: ", trs[['year']]))
    NULL
  } else {
    print(paste0("case: ",c," Year: ",trs[['year']]," Start: ",trs[['start']]," End: ",trs[['end']]))
    ann.dts[c,'case'] <- c
    ann.dts[c,'dt.min'] <- trs[['start']]
    ann.dts[c,'dt.max'] <- trs[['end']]
  }
}

# ``` load historical data ----------------------------------------------------

dsm2_filename <- paste0(dsm2.dir,'historical/anninputs/dsm2_ann_inputs_historical.xlsx')

for (sheet in sheetlist){
  assign(sheet,load_delta_vars(dsm2_filename, sheet))
}

# Combine all but base_ec_output
for (var in sheetlist[-length(sheetlist)]) {
  vardf <- get(var)
  if (var==sheetlist[1]){
    delta_state <- vardf
  } else {
    delta_state <- merge(delta_state, vardf, by='Time')
  } # end if var==sheetlist[1]
} # end for var in sheetlist
names(delta_state) <- append(c('Time'), sheetnames)
names(base_ec_output) <- append(c('Time'),names(base_ec_output)[2:ncol(base_ec_output)])
delta_state$`Net Delta Outflow` <- delta_state$`Northern Flow` + delta_state$`SJR Flow` - delta_state$Exports - 
  delta_state$`Consump Use`

ds.df <- melt(delta_state, id.vars='Time')
ds.df$case <- 'hist'
ec.df <- melt(base_ec_output, id.vars='Time')
ec.df$case <- 'hist'



# ``` load experimental data --------------------------------------------------

sheetlist <- c("northern_flow","sjr_flow","exports","dxc_gate_fraction",
               "suisun_gate_fraction","net_delta_cu","mtz_tidal_nrg",
               "base_ec_output")
sheetnames <- c('Northern Flow', 'SJR Flow','Exports','DCC Gate',
                'Suisun Gate','Consump Use','Tidal Nrg')
multipliers <- c(-35.314666212661, -35.314666212661, 35.314666212661, 0.1,
                 1, -35.314666212661, 3.28084)
# cases <- c(4,5)
mesh <- 'baseline'
c <- 4
schism_dir <- "D:/projects/delta_salinity/scripts/DSP_code/scripts/post-processing/data_out/schism_lhc_v3"


schism_vars <- c("Northern.Flow.In..cms.", "sjr.In..cms.","Exports.Combined.In..cms.","DCC.Gate.In",
                 "Suisun.Radial.In","Net.Delta.CU.In..cms.","Tidal.Energy.In")

for (c in cases) {
  print(c)
  # load delta state vars
  inout_fn <- paste0(schism_dir,"/",mesh,"_lhc_",c,".csv")
  
  # Get all but base_ec_output
  inout.df <- read.csv(inout_fn)
  inout.df$datetime <- lubridate::ymd_hms(inout.df$X0)
  delta_state <- inout.df[,append(c('datetime'), schism_vars)]
  
  names(delta_state) <- append(c('datetime'), sheetnames)
  # names(base_ec_output) <- append(c('Time'),names(base_ec_output)[2:ncol(base_ec_output)])
  
  # trim to case
  delta_state <- delta_state[delta_state$datetime>=lhc.dts$dt.min[c] & delta_state$datetime<=lhc.dts$dt.max[c],]
  delta_state[, -1] <- sweep(delta_state[, -1], 2, multipliers, `*`)
  
  # daily average
  delta_state <- delta_state %>%
    mutate(Time = as.Date(datetime)) %>%
    group_by(Time) %>%
    summarise(across(-datetime, mean, na.rm = TRUE))
  
  delta_state$`Net Delta Outflow` <- delta_state$`Northern Flow` + delta_state$`SJR Flow` - delta_state$Exports - 
    delta_state$`Consump Use`
  
  dsdum <- melt(delta_state, id.vars='Time')
  dsdum$case <- c
  # ecdum <- melt(base_ec_output, id.vars='Time')
  # ecdum$case <- c
  # print(paste0("Min EC time: ", min(ecdum$Time), " Max EC Time: ", max(ecdum$Time)))
  
  ds.df <- rbind(ds.df, dsdum)
  # ec.df <- rbind(ec.df, ecdum)

  rm(list=(c('dsdum')))
  
} # end case loop for exp data load

# ds.df$Time <- lubridate::ymd(ds.df$Time)
# ec.df$Time <- lubridate::ymd(ec.df$Time)

ds.df$case <- factor(ds.df$case,
                     levels=plt.vars)
# ec.df$case <- factor(ec.df$case,
#                      levels=plt.vars)

ds.date.lims <- c(min(ds.df$Time[ds.df$case %in% cases]),
                  max(ds.df$Time[ds.df$case %in% cases]))
# ec.date.lims <- c(min(ec.df$Time[ec.df$case %in% cases]),
#                   max(ec.df$Time[ec.df$case %in% cases]))

# Plot inputs -------------------------------------------------------------


# unique(ds.df$variable)

plt <- ggplot(data=ds.df) + 
  geom_line(aes(x=Time, y=value, color=case)) +
  facet_wrap(~variable, ncol=1, scales='free_y') +
  scale_x_date(limits=ds.date.lims) + 
  ggh4x::scale_y_facet(
    variable == "Northern Flow",
    trans  = "log10",
    breaks = breaks_log(),
    labels = label_log()
  ) +
  ggh4x::scale_y_facet(
    variable == "SJR Flow",
    trans  = "log10",
    breaks = breaks_log(),
    labels = label_log()
  ) +
  ggh4x::scale_y_facet(
    variable == "Net Delta Outflow",
    trans  = "log10",
    breaks = breaks_log(),
    labels = label_log()
  ) +
  ylab('') +
  xlab('') +
  scale_color_manual(values=var.cols, breaks=plt.vars)

# plt

pltl <- ggplotly(plt, dynamicTicks=TRUE)
pltl


pltl_name <- paste0("SCHISM_Input_Check_v",exp.num,".html")

saveWidget(pltl, pltl_name, selfcontained=TRUE)
file.rename(pltl_name, paste0("plots/",pltl_name))
