bash simulations/baseline_lhc_1/dsp_baseline_lhc_1.tropic.sh
bash simulations/suisun_lhc_1/dsp_suisun_lhc_1.tropic.sh
bash simulations/cache_lhc_1/dsp_cache_lhc_1.tropic.sh
bash simulations/baseline_lhc_2/dsp_baseline_lhc_2.tropic.sh
bash simulations/suisun_lhc_2/dsp_suisun_lhc_2.tropic.sh
bash simulations/cache_lhc_2/dsp_cache_lhc_2.tropic.sh
bash simulations/baseline_lhc_3/dsp_baseline_lhc_3.tropic.sh
bash simulations/suisun_lhc_3/dsp_suisun_lhc_3.tropic.sh
bash simulations/cache_lhc_3/dsp_cache_lhc_3.tropic.sh
bash simulations/baseline_lhc_4/dsp_baseline_lhc_4.tropic.sh
bash simulations/suisun_lhc_4/dsp_suisun_lhc_4.tropic.sh
bash simulations/cache_lhc_4/dsp_cache_lhc_4.tropic.sh
bash simulations/baseline_lhc_5/dsp_baseline_lhc_5.tropic.sh
bash simulations/suisun_lhc_5/dsp_suisun_lhc_5.tropic.sh
bash simulations/cache_lhc_5/dsp_cache_lhc_5.tropic.sh
bash simulations/baseline_lhc_6/dsp_baseline_lhc_6.tropic.sh
bash simulations/suisun_lhc_6/dsp_suisun_lhc_6.tropic.sh
bash simulations/cache_lhc_6/dsp_cache_lhc_6.tropic.sh
bash simulations/baseline_lhc_7/dsp_baseline_lhc_7.tropic.sh
bash simulations/suisun_lhc_7/dsp_suisun_lhc_7.tropic.sh
bash simulations/cache_lhc_7/dsp_cache_lhc_7.tropic.sh
