bash lhc_1/baseline/dsp_baseline_lhc_1.tropic.sh
bash lhc_1/suisun/dsp_suisun_lhc_1.tropic.sh
bash lhc_1/cache/dsp_cache_lhc_1.tropic.sh
bash lhc_2/baseline/dsp_baseline_lhc_2.tropic.sh
bash lhc_2/suisun/dsp_suisun_lhc_2.tropic.sh
bash lhc_2/cache/dsp_cache_lhc_2.tropic.sh
bash lhc_3/baseline/dsp_baseline_lhc_3.tropic.sh
bash lhc_3/suisun/dsp_suisun_lhc_3.tropic.sh
bash lhc_3/cache/dsp_cache_lhc_3.tropic.sh
bash lhc_4/baseline/dsp_baseline_lhc_4.tropic.sh
bash lhc_4/suisun/dsp_suisun_lhc_4.tropic.sh
bash lhc_4/cache/dsp_cache_lhc_4.tropic.sh
bash lhc_5/baseline/dsp_baseline_lhc_5.tropic.sh
bash lhc_5/suisun/dsp_suisun_lhc_5.tropic.sh
bash lhc_5/cache/dsp_cache_lhc_5.tropic.sh
bash lhc_6/baseline/dsp_baseline_lhc_6.tropic.sh
bash lhc_6/suisun/dsp_suisun_lhc_6.tropic.sh
bash lhc_6/cache/dsp_cache_lhc_6.tropic.sh
bash lhc_7/baseline/dsp_baseline_lhc_7.tropic.sh
bash lhc_7/suisun/dsp_suisun_lhc_7.tropic.sh
bash lhc_7/cache/dsp_cache_lhc_7.tropic.sh
