# Define Environmental Variables  ---------------------------------------------------------------

env_vars: # env_vars are used to populate the rest of the variables below
- dsp_home: /scratch/tomkovic/DSP_code # where the main folder of this project is (HPC4)
- bds_home: /home/tomkovic/BayDeltaSCHISM # where the BayDeltaSCHISM repository is housed
- experiment: lhc_v3 # name of folder to look inside of test_file for azure setup
- schism_dir: '{dsp_home}/model/schism'
- exp_dir: '{schism_dir}/azure_dsp_2024_{experiment}'
- common_dir: '{exp_dir}'
- mc_dir: '{exp_dir}/simulations/{mesh}_lhc_{case_num}'

mod_th_dict: '{meshcase_dir}/mod_th_dict_lhc_{case_num}.yaml'

out_dir: '{dsp_home}/scripts/ann_training/data_out/schism_{experiment}' # where the ANN-ready data will go

station_in: '{exp_dir}/station.in'
flux_in: '{exp_dir}/flow_station_xsects.yaml'

# Input Variables to the ANN --------------------------------------------------------------------

in_vars:
- name: Northern Flow #{'RSAC155': hist_dss_file, 'BYOLO040': hist_dss_file, 'RMKL070': hist_dss_file, 'RCSM075': hist_dss_file, 'RCAL009': hist_dss_file, 'SLBAR002': hist_dss_file}
  th_files: 
    - '{flux_file}'
  th_header: '{bds_home}/data/time_history/flux.th' # use this to get the headers to match the inputs
  inputs:
    - sac # Sacramento River - RSAC155
    - yolo # Yolo Bypass
    - yolo_toedrain # Yolo Toe Drain - BYOLO040
    - east # Mokelumne/Cosumnes - RMKL070 & RCSM075
    - calaveras # Calaveras - RCAL009
    - -northbay # North Bay Aqueduct (negative) -  SLBAR002
  method: read_multiple_column_th

- name: SJR Flow
  th_files: 
    - '{flux_file}'
  th_header: '{bds_home}/data/time_history/flux.th' # use this to get the headers to match the inputs
  inputs:
    - sjr
  method: read_single_column_th

- name: Exports # Sum(Banks, Jones, CCC plants(Rock Sl, Middle R (actually old river), Victoria))
  th_files: 
    - '{flux_file}'
  header_in:
    - '{meshcase_dir}/flow_station_xsects.yaml'
  th_header: '{bds_home}/data/time_history/flux.th' # use this to get the headers to match the inputs
  inputs:
    - swp # Banks
    - cvp # Jones
    - ccc_rock # CCC Rock Sl
    - ccc_old # CCC Middle R/Old R
    - ccc_victoria # CCC Victoria
  method: read_multiple_column_th

- name: DCC Gate
  th_files: 
    - '{dcc_file}'
  th_header: '{bds_home}/data/time_history/delta_cross_channel.th' # use this to get the headers to match the inputs
  inputs:
    - op_up # this is what will consider the operation of the gate (1=Open, 0=Closed)
  method: read_single_column_th

- name: Suisun Gate
  th_files: 
    - '{smscg_file}'
  th_header: '{bds_home}/data/time_history/montezuma_radial.th' # use this to get the headers to match the inputs
  inputs:
    - op_up # this is what will consider the operation of the gate (1=Open, 0=Tidally Operated)
  method: read_single_column_th

- name: Net Delta CU # daily (DIV+SEEP-DRAIN) for DCD and SMCD 
  th_files: 
    - '{vsource_file}'
    - '{vsink_file}'
  method: calc_dcu

- name: Tidal Energy
  station_output: '{meshcase_dir}/outputs/staout_1'
  loc:
    - sffpx # San Francisco
  method: calc_tidal_energy

- name: Rio Vista Outflow
  flux_output: '{meshcase_dir}/outputs/flux.out'
  loc:
    - srv # Rio Vista
  method: read_single_flux

# Output Variables to the ANN -------------------------------------------------------------------

out_vars:
- station_output: '{meshcase_dir}/outputs/staout_6'
- param_clinic: '{meshcase_dir}/param.nml.clinic'
- ec_locs:
  - trp # 'CHDMC006' CVP Intake at Tracy Pumping Plant
  - wci # 'CHSWP003' West Canal near Clifton Court Intake
  - vcu # 'CHVCT000' Victoria Canal
  # - uni # 'OLD_MID' Old River near Middle River
  - obi # 'ROLD024' Old R at Bacon Island
  # - old # 'ROLD059' Old River at Tracy Blvd 
  - pct # 'RSAC064' Sacramento River at Port Chicago 
  - mal # 'RSAC075': Sacramento River at Mallard Island
  - cse # 'RSAC081' Sacramento River at Collinsville 
  - emm2 #'RSAC101' Sacramento River at Emmaton
  - anh # 'RSAN007' San Joaquin at Antioch
  - jer # 'RSAN018' Jersey point
  - sal # 'RSAN032' San Andreas Landing 
  - ppt # 'RSAN037' Prisoners Point 
  # - rri2 # 'RSAN058' Rough and Ready Island
  # - bdt # 'RSAN072' San Joaquin River at Brandt Bridge
  # - lps # 'RSMKL008' Little Potato Slough at Terminous 
  # - snc # 'SLCBN002' Chadbourne Slough at Sunrise Duck Club 
  - dsj # 'SLDUT007' Dutch Sl below Jersey Island
  - bdl # 'SLMZU011' Montezuma Slough near Beldons Landing  
  - nsl2 # 'SLMZU025' Montezuma Slough at National Steel
  - vol # 'SLSUS012' Suisun Slough 300' south of Volanti Slough
  # - tss # 'SLTRM004' Threemile Slough near San Joaquin River 
  # - sss # 'SSS' Steamboat Slough btw Sacramento R and Sutter Sl 
  # - carqb #'RSAC054' Carquinez Strait at Carquinez Bridge near Crockett
  # Stations not in DSM2 ------------------------------------
  - inb # 'SLRCK005' CWD Rock Slough PP
  - srv # 'RSAC101' Sacramento R at Rio Vista
  - oh4 # 'OH4' Old R near Byron
  - hll # 'HLL' Holland Tract
  - bet # 'BET' Piper Slough at Bethal Tract
  - ibs # 'IBS' Cordelia Slough at Ibis club
  - gys # 'GYS' Goodyear Slough at Morrow Island clu

# Model Meshes ----------------------------------------------------------------------------------

meshes:
- baseline
- suisun
- cache

# Model Cases -----------------------------------------------------------------------------------

cases:
- case_num: 1
- case_num: 2
- case_num: 3
- case_num: 4
- case_num: 5
- case_num: 6
- case_num: 7
