dsp_home: D:/projects/delta_salinity/scripts/DSP_code # where the main folder of this project is

experiment: historical # name of folder to look inside of test_file dir

base_study_folder: '{dsp_home}/model/dsm2/2021DSM2FP_202301'
model_input_folder: '{base_study_folder}/timeseries'
model_folder: '{dsp_home}/model/dsm2/DSP_DSM2_202307/{experiment}'
model_output_folder: '{model_folder}/output'

# dcd_dss_file: '{dsp_home}/model/dsm2/DSP_DSM2_202307/historical/timeseries/DCD_hist_Sep2020_Lch5.dss'
# smcd_dss_file: '{dsp_home}/model/dsm2/DSP_DSM2_202307/historical/timeseries/SMCD_hist_Sep2020.dss'

# hist_dss_file: '{dsp_home}/model/dsm2/DSP_DSM2_202307/historical/timeseries2019/hist201912.dss'
# gate_dss_file: '{dsp_home}/model/dsm2/DSP_DSM2_202307/historical/timeseries2019/gates-v8-201912.dss   '
# model_ec_file: '{dsp_home}/model/dsm2/DSP_DSM2_202307/historical/hist19smcd/output/hist_v82_19smcd.dss'
# output_folder: '{model_folder}/hist19smcd/anninputs'
# xlsx_filepath: '{model_folder}/hist19smcd/anninputs/dsm2_ann_inputs_{experiment}.xlsx'

dcd_dss_file: '{base_study_folder}/timeseries/DCD_hist_Lch5.dss'
smcd_dss_file: '{base_study_folder}/timeseries/SMCD_hist.dss'

hist_dss_file: '{base_study_folder}/timeseries/hist.dss'
gate_dss_file: '{base_study_folder}/timeseries/gates-v8.dss'
model_ec_file: '{model_folder}/output/hist_v2023_01_EC.dss'
output_folder: '{model_folder}/anninputs'
xlsx_filepath: '{model_folder}/anninputs/dsm2_ann_inputs_{experiment}.xlsx'
