
#dsp_home: D:/projects/delta_salinity/scripts/DSP_code # where the main folder of this project is

dsp_home: F:/ann_workspace/DSP_code

experiment: latinhypercube_v2 # name of folder to look inside of test_file dir

base_study_folder: '{dsp_home}/model/dsm2/2021DSM2FP_202301'
model_input_folder: '{base_study_folder}/timeseries'
model_folder: '{dsp_home}/model/dsm2/DSP_DSM2_202307/{experiment}'
model_output_folder: '{model_folder}/output'

smcd_dss_file: '{model_input_folder}/SMCD_hist.dss'

dcd_dss_file: '{model_folder}/timeseries/lhc_{case_num}_dcd.dss'
hist_dss_file: '{model_folder}/timeseries/lhc_{case_num}_hist.dss'
gate_dss_file: '{model_folder}/timeseries/lhc_{case_num}_gates.dss'
model_ec_file: '{model_output_folder}/lhc_{case_num}_EC.dss'
output_folder: '{dsp_home}/model/dsm2/DSP_DSM2_202307/{experiment}/anninputs/lhc_{case_num}'
# output_folder: '{dsp_home}/model/dsm2/DSP_DSM2_202307/latinhypercube_v1p1/anninputs/lhc_{case_num}'
xlsx_filepath: '{dsp_home}/model/dsm2/DSP_DSM2_202307/{experiment}/anninputs/dsm2_ann_inputs_lhc_{case_num}.xlsx'
# xlsx_filepath: '{dsp_home}/model/dsm2/DSP_DSM2_202307/latinhypercube_v1p1/anninputs/dsm2_ann_inputs_lhc_{case_num}.xlsx'
cases:
- case_num: 1
- case_num: 2
- case_num: 3
- case_num: 4
- case_num: 5
- case_num: 6
- case_num: 7
