#dsp_home: D:/projects/delta_salinity/scripts/DSP_code # where the main folder of this project is

dsp_home: F:/ann_workspace/DSP_code

experiment: latinhypercube_v3 # name of folder to look inside of test_file dir

test_files:
- '{dsp_home}/model/dsm2/DSP_DSM2_202307/historical/anninputs/dsm2_ann_inputs_historical.xlsx'

test_windows:
- start:
  - 2007-10-1
  - 2009-10-1
  - 2011-10-1
  - 2013-10-1
- end:
  - 2008-9-30
  - 2010-9-30
  - 2012-9-30
  - 2014-9-30

vars_include:
- northern_flow
- sjr_flow
- exports
- dxc_gate_fraction
- suisun_gate_fraction
- net_delta_cu
- mtz_tidal_nrg
- base_ec_output

# stas_include:
# - CHDMC006
# - CHSWP003
# - CHVCT000
# - ROLD024
# - RSAC075
# - RSAC081
# - RSAC092
# - RSAN018
# - SLMZU011
# - SLRCK005
# - RSAN032

stas_include:
- CHDMC006 # CVP
- CHSWP003 # SWP
- CHVCT000 # CCV
- ROLD024 # BAC
- RSAC075 # Mallard
- RSAC081 # cll
- RSAC092 # emm
- RSAN018 # jer
- SLMZU011 # BDL
- SLRCK005 # Rock Slough
- RSAN032 # san andreas
- RSAC101 # SRV
- RSAN007 # ANT
#- ROLD034 # OH4
#- TMS # Needs to be added to DSM2 output for TMS



train_config: # a dictinoary to take the place of train_files and train_windows
- num: 0
  year: 1997
  file: '{dsp_home}/model/dsm2/DSP_DSM2_202307/historical/anninputs/dsm2_ann_inputs_historical.xlsx'
  start: 1997-5-1
  end: 1997-9-1
- num: 1
  year: 2014
  file: '{dsp_home}/model/dsm2/DSP_DSM2_202307/{experiment}/anninputs/dsm2_ann_inputs_lhc_1.xlsx'
  start: 2014-1-1
  end: 2015-5-31
- num: 2
  year: 2012
  file: '{dsp_home}/model/dsm2/DSP_DSM2_202307/{experiment}/anninputs/dsm2_ann_inputs_lhc_2.xlsx'
  start: 2012-1-1
  end: 2012-12-31
- num: 3
  year: 2014
  file: '{dsp_home}/model/dsm2/DSP_DSM2_202307/{experiment}/anninputs/dsm2_ann_inputs_lhc_3.xlsx'
  start: 2014-1-1
  end: 2015-5-31
- num: 4
  year: 2008
  file: '{dsp_home}/model/dsm2/DSP_DSM2_202307/{experiment}/anninputs/dsm2_ann_inputs_lhc_4.xlsx'
  start: 2007-2-1
  end: 2008-5-31
- num: 5
  year: 2008
  file: '{dsp_home}/model/dsm2/DSP_DSM2_202307/{experiment}/anninputs/dsm2_ann_inputs_lhc_5.xlsx'
  start: 2007-2-1
  end: 2008-5-31
- num: 6
  year: 2012
  file: '{dsp_home}/model/dsm2/DSP_DSM2_202307/{experiment}/anninputs/dsm2_ann_inputs_lhc_6.xlsx'
  start: 2012-1-1
  end: 2012-12-31
- num: 7
  year: 2010
  file: '{dsp_home}/model/dsm2/DSP_DSM2_202307/{experiment}/anninputs/dsm2_ann_inputs_lhc_7.xlsx'
  start: 2010-5-1
  end: 2011-5-31


models: 
- name: lstm
  params:
    - 12

excel_files:
- '{dsp_home}/model/dsm2/DSP_DSM2_202307/historical/anninputs/dsm2_ann_inputs_historical.xlsx'